#FROM mysql/mysql-server:8.0.23
#
##RUN apt-get update && apt-get install -y vim
#RUN apk update && apk add --no-cache vim
#
#ENV VISUAL=vim
#ENV EDITOR=vim
#ENV         MAVEN_HOME /apache-maven-3.9.4
#ENV         PATH $MAVEN_HOME/bin:$PATH
#COPY        my.cnf /etc/my.cnf